import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'


// API endpoint where we send form data.
const endpoint = '/api/users/get_all_users';

// Form the request for sending data to the server.
const options = {
  // The method is POST because we are sending data.
  method: 'GET',
  // Tell the server we're sending JSON.
  headers: {
    'Content-Type': 'application/json',
  },
};

const GetAllUsersPage: NextPage = () => {

  const [data, setData] = useState([]);
  const [error, setError] = useState('');

  const loadUsers = () => {
    fetch(endpoint, options).
      then(async (response) => {
        const isJson = response.headers.get('content-type')?.includes('application/json');
        const data = isJson ? await response.json() : null;

        // check for error response
        if (!response.ok) {
          // get error message from body or default to response status
          const error = data?.error?.message || response.status;
          return Promise.reject(error);
        }

        if (data.result) {
          setData(data.result);
        }
      }).
      catch(reason => {
        setError(reason);
      });
  }

  // Handles the submit event on form submit.
  const handleSubmit = async (event: SubmitEvent) => {
    // Stop the form from submitting and refreshing the page.
    event.preventDefault()

    // Send the data to the server in JSON format.
    const JSONdata = JSON.stringify(data);

    // Form the request for sending data to the server.
    const options = {
      // The method is POST because we are sending data.
      method: 'POST',
      // Tell the server we're sending JSON.
      headers: {
        'Content-Type': 'application/json',
      },
      // Body of the request is the JSON data we created above.
      body: JSONdata,
    };

    // Send the form data to our forms API on Vercel and get a response.
    const response = await fetch(endpoint, options);
  };

  useEffect(() => loadUsers());

  return (
    <div>
      <Head>
        <title>Or Linzer Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>
          Get All Users
        </h1>
      </header>

      <main>
        <p style={{ color: 'red' }}>{error}</p>
        {JSON.stringify(data)}

        {/* <form action="/api/set_user" method="post"> */}
        {/* <form onSubmit={handleSubmit}>
          <button type="submit">Submit</button>
        </form> */}
      </main>

      <footer>
        Or Linzer
      </footer>
    </div>
  )
}

export default GetAllUsersPage;
