import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const firstNameRef = useRef(null);
  const lastNameRef = useRef(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Or Linzer Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className={styles.title}>
          Welcome to Or Linzer Website
        </h1>
      </header>

      <main className={styles.main}>
        <form action="/api/set_user" method="post">
          {/* <label htmlFor={firstNameRef}>First name:</label>
          <input type="text" ref={firstNameRef} name="first" /> */}
          <label >First name:</label>
          <input type="text" name="first" />
          <label >Last name:</label>
          <input type="text" name="last" />
          <button type="submit">Submit</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
